server:
  port: 8080

spring:
  application:
    name: titanwalkers

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: "titan.html"   # http://localhost:{port}/titan.html
    tags-sorter: "alpha"
