server:
  port: 8080

spring:
  application:
    name: titanwalkers

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: "titan.html"   # http://localhost:{port}/titan.html
    tags-sorter: "alpha"
  paths-to-match: "/v1"
